source 'https://rubygems.org'

ruby '>= 2.6.10'

gem 'cocoapods', '~> 1.15'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
gem 'fastlane'
gem 'slop'
gem 'fileutils'
gem 'dot-properties'
gem 'json'
gem 'mini_magick'
gem 'cocoapods-repo-update'
gem 'dotenv'
gem 'plist'
gem 'xcodeproj'
gem 'git'
gem 'nokogiri'
gem 'cocoapods-user-defined-build-types'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
